# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификтор')),
                ('second_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=128, verbose_name='Отчество')),
                ('photo', models.URLField(verbose_name='Фотография')),
                ('groupName', models.CharField(max_length=32, verbose_name='Группа')),
                ('vk', models.URLField(max_length=64, verbose_name='Идентификатор вк')),
                ('telegram', models.CharField(max_length=64, verbose_name='Идентификтор telegram')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('public_fields', models.TextField(verbose_name='Доступные поля')),
            ],
        ),
        migrations.CreateModel(
            name='CurTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификтор')),
                ('name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('order', models.IntegerField(verbose_name='Фамилия')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('manual', models.TextField(verbose_name='Инструкция')),
                ('available', models.BooleanField(verbose_name='Доступность')),
                ('from_to', models.DurationField(verbose_name='Срок')),
                ('stat_factor', models.FloatField(verbose_name='Коэффициент кураторского часа')),
            ],
        ),
        migrations.CreateModel(
            name='CurTimeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата проведения')),
                ('cur_rating', models.CharField(max_length=255, verbose_name='Рейтинг кч')),
                ('group_rating', models.CharField(max_length=255, verbose_name='Рейтинг внутригруппового настроя')),
                ('cur_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurator_base.CurTime')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификтор')),
                ('prefix', models.CharField(max_length=8, verbose_name='Префикс')),
                ('number', models.IntegerField(verbose_name='Номер группы')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurator_base.Curator')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификтор')),
                ('second_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
            ],
        ),
        migrations.AddField(
            model_name='curtimeresult',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurator_base.Group'),
        ),
    ]
