# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurator_base', '0004_auto_20170826_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curator',
            options={'ordering': ['last_name'], 'verbose_name': 'Куратор', 'verbose_name_plural': 'Кураторы'},
        ),
    ]
