# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurator_base', '0005_auto_20170826_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StudentGroup',
        ),
    ]
